In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('carpricesDummy.csv')

In [13]:
# for removing the spaces from table
df.columns = df.columns.str.replace(' ', '_')

In [16]:
dummyPd = pd.get_dummies(df.Car_Model)

In [17]:
newDf = pd.concat([df,dummyPd], axis='columns')

In [29]:
finalDf = newDf.drop(['Car_Model','Audi A5'],axis='columns')

finalDf.columns = finalDf.columns.str.replace('(', '_')
finalDf.columns = finalDf.columns.str.replace(')', '')
finalDf.columns = finalDf.columns.str.replace(' ', '_')
finalDf

C:\Users\PRANABESH DEY\AppData\Local\Temp\ipykernel_11984\45773996.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  finalDf.columns = finalDf.columns.str.replace('(', '_')
C:\Users\PRANABESH DEY\AppData\Local\Temp\ipykernel_11984\45773996.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  finalDf.columns = finalDf.columns.str.replace(')', '')


Mileage  Sell_Price_$  Age_yrs  BMW_X5  Mercedez_Benz_C_class
0     69000         18000        6       1                      0
1     35000         34000        3       1                      0
2     57000         26100        5       1                      0
3     22500         40000        2       1                      0
4     46000         31500        4       1                      0
5     59000         29400        5       0                      0
6     52000         32000        5       0                      0
7     72000         19300        6       0                      0
8     91000         12000        8       0                      0
9     67000         22000        6       0                      1
10    83000         20000        7       0                      1
11    79000         21000        7       0                      1
12    59000         33000        5       0                      1

In [31]:
X = finalDf[['Mileage','Age_yrs','BMW_X5','Mercedez_Benz_C_class']]
X

Mileage  Age_yrs  BMW_X5  Mercedez_Benz_C_class
0     69000        6       1                      0
1     35000        3       1                      0
2     57000        5       1                      0
3     22500        2       1                      0
4     46000        4       1                      0
5     59000        5       0                      0
6     52000        5       0                      0
7     72000        6       0                      0
8     91000        8       0                      0
9     67000        6       0                      1
10    83000        7       0                      1
11    79000        7       0                      1
12    59000        5       0                      1

In [34]:
Y = finalDf[['Sell_Price_$']]

In [35]:
Y

Sell_Price_$
0          18000
1          34000
2          26100
3          40000
4          31500
5          29400
6          32000
7          19300
8          12000
9          22000
10         20000
11         21000
12         33000

In [36]:
model = LinearRegression()
model.fit(X,Y)

LinearRegression()

In [37]:
model.predict([[70000,5,0,0]])

C:\AnacondaProgram\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[23952.27048603]])

In [38]:
model.predict([[45000,4,0,1]])

C:\AnacondaProgram\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[36991.31721061]])

In [39]:
model.score(X,Y)

0.9417050937281082

In [40]:
model.predict([[86000,7,1,0]])

C:\AnacondaProgram\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[11080.74313219]])