In [1]:
import pandas as pd
from sklearn import linear_model
import numpy as np

In [2]:
df = pd.read_csv('homeprices.csv')

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.bedrooms.median()

4.0

In [5]:
import math
bedroom_median = math.floor(df.bedrooms.median())
bedroom_median

4

In [6]:
df.bedrooms = df.bedrooms.fillna(bedroom_median)

In [7]:
# df = df[:5]
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [8]:
model = linear_model.LinearRegression()

In [9]:
model.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [10]:
model.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [11]:
model.intercept_

221323.00186540408

In [12]:
model.predict([[3000,3,40]])

C:\AnacondaProgram\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [13]:
112.06244194*3000+23388.88007794*3+-3231.71790863*40+221323.00186540408

498408.2515740241

In [14]:
model.predict([[2500,4,5]])

C:\AnacondaProgram\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])