# Numpy

In [1]:
print("Hello world")

Hello world


In [2]:
import numpy as np

In [3]:
arrays1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arrays1)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [4]:
arrays1.shape

(2, 5)

In [5]:
arrays1.dtype

dtype('int32')

In [6]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
arrays1*arrays1

array([[ 1,  4,  9, 16, 25],
       [ 1,  4,  9, 16, 25]])

In [8]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

# Slicing

In [9]:
arrays1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [10]:
arrays1[3:4]

array([], shape=(0, 5), dtype=int32)

In [11]:
arrays2 = np.array([2,3,4,5,6,9])

In [41]:
arr = arrays2[2:5]

In [42]:
arr

array([4, 8, 6])

In [14]:
arr[1] = 8

In [15]:
arrays2

array([2, 3, 4, 8, 6, 9])

In [16]:
arr1 = arrays2[2:5].copy()

In [17]:
arr1[2] = 10

In [18]:
arrays2

array([2, 3, 4, 8, 6, 9])

In [19]:
arr1

array([ 4,  8, 10])

In [20]:
arrays1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [21]:
arrays1[1,2:4]

array([3, 4])

In [22]:
array3 = np.array([[1,2,3,4,5],[9,7,5,3,2]])

In [23]:
array3

array([[1, 2, 3, 4, 5],
       [9, 7, 5, 3, 2]])

In [24]:
array3.sum(axis=0) # 0 for column operation

array([10,  9,  8,  7,  7])

In [25]:
array3.sum(axis=1) #1 for row operation

array([15, 26])

In [29]:
arrays1

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [31]:
arrays1.dot(array3.transpose()) #Dot product

array([[55, 60],
       [55, 60]])

In [34]:
array4 = np.arange(10)
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
array4.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

# Sorting

In [35]:
array5 = ([21,4,5,6,43,3,4,3,2,2,6,8,9])

In [36]:
np.argsort(array5) # This will show the index of smaller value to greater value ascending order 

array([ 8,  9,  5,  7,  1,  6,  2,  3, 10, 11, 12,  0,  4], dtype=int64)

In [37]:
np.argmin(array5) # show the index of min value

8

In [38]:
np.argmax(array5) # show the index of max value

4