In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn.metrics import mean_squared_error 

In [4]:
from sklearn.linear_model import LinearRegression

In [5]:
import matplotlib.pyplot as plt
%matplotlib tk

In [6]:
df = pd.read_csv('score_updated.csv')

In [7]:
x = np.array(df.Hours).reshape(-1,1)
x.dtype

dtype('float64')

In [8]:
y = np.array(df.Scores).reshape(-1,1)
y.dtype

dtype('int64')

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [11]:
model = LinearRegression()

In [12]:
model.fit(x_train,y_train)

LinearRegression()

In [13]:
model.score(x_test,y_test)

0.9728967035119018

In [14]:
y_predict = model.predict(x_test)
# y_predict

In [15]:
plt.scatter(x_test,y_test)

In [16]:
plt.plot(x_test,y_predict)
plt.title('Study hours Vs Score of students')
plt.xlabel('Hours')
plt.ylabel('Score')

Text(0, 0.5, 'Score')

In [17]:
# plt.figure(figsize=(10,5))

In [18]:
model.coef_

array([[9.88266515]])

In [19]:
model.intercept_

array([2.3100576])

In [20]:
model.predict([[10]])

array([[101.13670914]])

In [21]:
10*9.78455038+2.39357503

100.23907883

In [22]:
mean_squared_error(y_test,y_predict)

16.60204208375356